const products = [
  {
    name: "Maggy Stanley",
    description: "vulputate, posuere vulputate,",
    categoryid: 10,
    id: 7716,
  },
  {
    name: "Raymond Albert",
    description: "mattis. Cras eget nisi",
    categoryid: 2,
    id: 7306,
  },
  {
    name: "Berk Blair",
    description: "ante lectus convallis est, vitae sodales nisi",
    categoryid: 6,
    id: 1178,
  },
  {
    name: "Sopoline Cohen",
    description: "in, dolor. Fusce",
    categoryid: 19,
    id: 4919,
  },
  {
    name: "Olivia Raymond",
    description: "Nulla eu neque pellentesque",
    categoryid: 7,
    id: 8480,
  },
  {
    name: "Kieran Morgan",
    description: "mauris. Integer sem elit, pharetra ut,",
    categoryid: 4,
    id: 5029,
  },
  {
    name: "Colette Serrano",
    description: "Nulla facilisi. Sed neque. Sed",
    categoryid: 4,
    id: 9896,
  },
  {
    name: "Martin Cantu",
    description: "ultrices posuere cubilia",
    categoryid: 3,
    id: 9929,
  },
  {
    name: "Linda Morin",
    description: "placerat, augue. Sed",
    categoryid: 14,
    id: 8392,
  },
  {
    name: "Dana Henry",
    description: "semper auctor. Mauris",
    categoryid: 5,
    id: 5376,
  },
  {
    name: "Palmer Ferrell",
    description: "rutrum eu, ultrices sit amet, risus. Donec",
    categoryid: 4,
    id: 5589,
  },
  {
    name: "Inez Slater",
    description: "lorem ut aliquam iaculis, lacus pede sagittis",
    categoryid: 5,
    id: 5210,
  },
  {
    name: "Quinlan Rosales",
    description: "leo. Cras vehicula aliquet libero. Integer",
    categoryid: 7,
    id: 8196,
  },
  {
    name: "Quinn Washington",
    description: "ullamcorper. Duis at lacus. Quisque purus sapien, gravida",
    categoryid: 9,
    id: 1982,
  },
  {
    name: "Destiny Gardner",
    description: "magna a neque. Nullam ut nisi a",
    categoryid: 3,
    id: 4840,
  },
  {
    name: "Austin Snow",
    description: "gravida sagittis. Duis gravida. Praesent eu",
    categoryid: 1,
    id: 1958,
  },
  {
    name: "Dane Walter",
    description: "et ultrices",
    categoryid: 8,
    id: 4121,
  },
  {
    name: "Evelyn Andrews",
    description: "tempor arcu. Vestibulum ut eros non enim",
    categoryid: 13,
    id: 8524,
  },
  {
    name: "Rhoda Head",
    description: "nascetur ridiculus mus.",
    categoryid: 13,
    id: 8367,
  },
  {
    name: "Graiden Dyer",
    description: "quis diam.",
    categoryid: 19,
    id: 4694,
  },
  {
    name: "Jamal Flowers",
    description: "in, cursus et, eros. Proin",
    categoryid: 2,
    id: 6615,
  },
  {
    name: "Neville Bridges",
    description: "vulputate, posuere vulputate, lacus. Cras interdum.",
    categoryid: 17,
    id: 9103,
  },
  {
    name: "Hop Ramos",
    description: "eu tellus. Phasellus elit pede,",
    categoryid: 16,
    id: 7214,
  },
  {
    name: "Ora Patton",
    description: "Ut tincidunt orci quis lectus. Nullam",
    categoryid: 10,
    id: 2257,
  },
  {
    name: "Moana Harrell",
    description: "eget ipsum. Suspendisse sagittis. Nullam vitae diam.",
    categoryid: 3,
    id: 1669,
  },
  {
    name: "Pandora Gentry",
    description: "id enim. Curabitur massa. Vestibulum accumsan neque",
    categoryid: 18,
    id: 9512,
  },
  {
    name: "Signe Reid",
    description: "ante bibendum ullamcorper. Duis cursus,",
    categoryid: 8,
    id: 8888,
  },
  {
    name: "Chaim Frost",
    description: "vitae, erat.",
    categoryid: 3,
    id: 5130,
  },
  {
    name: "Trevor Allen",
    description: "blandit. Nam nulla magna, malesuada vel, convallis",
    categoryid: 15,
    id: 2764,
  },
  {
    name: "Fitzgerald Reid",
    description: "lorem lorem, luctus",
    categoryid: 5,
    id: 7297,
  },
  {
    name: "Zeph Mcdaniel",
    description: "elementum, lorem ut aliquam iaculis, lacus",
    categoryid: 6,
    id: 2310,
  },
  {
    name: "Heather Holloway",
    description: "sit amet, consectetuer adipiscing",
    categoryid: 7,
    id: 9136,
  },
  {
    name: "Jamal Hurst",
    description: "erat semper rutrum. Fusce",
    categoryid: 19,
    id: 9674,
  },
  {
    name: "Ira O'connor",
    description: "ornare, elit",
    categoryid: 14,
    id: 8690,
  },
  {
    name: "Brock Anderson",
    description: "Nullam velit dui, semper",
    categoryid: 20,
    id: 8398,
  },
  {
    name: "Uriah Guzman",
    description: "ut, nulla. Cras eu",
    categoryid: 5,
    id: 1874,
  },
  {
    name: "Colton English",
    description: "et arcu imperdiet ullamcorper.",
    categoryid: 18,
    id: 4676,
  },
  {
    name: "Ali Burch",
    description: "dictum eu, placerat",
    categoryid: 2,
    id: 2108,
  },
  {
    name: "Serina Hobbs",
    description: "fringilla mi lacinia mattis.",
    categoryid: 9,
    id: 9070,
  },
  {
    name: "Jena Sims",
    description: "vitae odio sagittis semper. Nam tempor",
    categoryid: 4,
    id: 2195,
  },
];
export default products;